/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author raula
 */
public class Datosfacturacion extends javax.swing.JFrame {

   String user;
   
    /**
     * Creates new form Datosfacturacion
     */
    public Datosfacturacion() {
        initComponents();
        user = Login.user;
              
        setTitle("Agregar datos de facturación - Sesión de " + user);
        setSize(600,600);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
           
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Logo1.jpg"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_RFC = new javax.swing.JTextField();
        txt_razonsocial = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        txt_MontoTotal = new javax.swing.JTextField();
        cmb_CFDI = new javax.swing.JComboBox<>();
        cmb_metodoPago = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos de facturación");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RFC");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Razón social:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("em@il:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Monto Total:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Método de pago:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Uso de CFDI:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        txt_RFC.setBackground(new java.awt.Color(153, 153, 255));
        txt_RFC.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_RFC.setForeground(new java.awt.Color(255, 255, 255));
        txt_RFC.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_RFC.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_RFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 450, -1));

        txt_razonsocial.setBackground(new java.awt.Color(153, 153, 255));
        txt_razonsocial.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_razonsocial.setForeground(new java.awt.Color(255, 255, 255));
        txt_razonsocial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_razonsocial.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_razonsocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 450, -1));

        txt_mail.setBackground(new java.awt.Color(153, 153, 255));
        txt_mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(255, 255, 255));
        txt_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mail.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txt_mail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mailActionPerformed(evt);
            }
        });
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 450, -1));

        txt_MontoTotal.setBackground(new java.awt.Color(153, 153, 255));
        txt_MontoTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_MontoTotal.setForeground(new java.awt.Color(255, 255, 255));
        txt_MontoTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_MontoTotal.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txt_MontoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MontoTotalActionPerformed(evt);
            }
        });
        txt_MontoTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MontoTotalKeyTyped(evt);
            }
        });
        getContentPane().add(txt_MontoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 450, -1));

        cmb_CFDI.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "P01 Por definir.", "D01 Honorarios médicos, dentales y gastos hospitalarios.", "D02 Gastos médicos por incapacidad o discapacidad.", "D03 Gastos funerales.", "D04 Donativos.", "D05 Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).", "D06 Aportaciones voluntarias al SAR.", "D07 Primas por seguros de gastos médicos.", "D08 Gastos de transportación escolar obligatoria.", "D09 Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.", "D10 Pagos por servicios educativos (colegiaturas).", "G01 Adquisición de mercancias.", "G02 Devoluciones, descuentos o bonificaciones.", "G03 Gastos en general.", "I01 Construcciones.", "I02 Mobiliario y equipo de oficina por inversiones.", "I03 Equipo de transporte.", "I04 Equipo de computo y accesorios.", "I05 Dados, troqueles, moldes, matrices y herramental.", "I06 Comunicaciones telefónicas.", "I07 Comunicaciones satelitales.", "I08 Otra maquinaria y equipo." }));
        getContentPane().add(cmb_CFDI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        cmb_metodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Efectivo", "Transferencia", "Depósito", "Tarjeta de Crédito/Débito" }));
        getContentPane().add(cmb_metodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AñadirUser.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 430, 120, 100));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoUni.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       int CFDI_cmb, metodoPago_cmb, validacion = 0;
       String RFC, razonsocial, mail, CFDI_string = "", metodoPago_string = "", MontoTotal;
       
       RFC = txt_RFC.getText().trim();
       razonsocial = txt_razonsocial.getText().trim();
       CFDI_cmb = cmb_CFDI.getSelectedIndex() + 1;
       metodoPago_cmb = cmb_metodoPago.getSelectedIndex() + 1;
       MontoTotal = txt_MontoTotal.getText().trim();
       mail = txt_mail.getText().trim();
      
        if(RFC.equals("")) {
           txt_RFC.setBackground(Color.red);
           validacion++;     
       }
       if(razonsocial.equals("")) {
           txt_razonsocial.setBackground(Color.red);
           validacion++;     
       }
       if(mail.equals("")) {
           txt_mail.setBackground(Color.red);
           validacion++;     
       }
       if(MontoTotal.equals("")) {
           txt_MontoTotal.setBackground(Color.red);
           validacion++;     
       }
       
            if(CFDI_cmb == 1) {
               CFDI_string = "Ninguno";
            } else if(CFDI_cmb == 2) {
               CFDI_string = "P01 Por definir.";
            } else if(CFDI_cmb == 3) {
               CFDI_string = "D01 Honorarios médicos, dentales y gastos hospitalarios.";
            } else if(CFDI_cmb == 4) {
               CFDI_string = "D02 Gastos médicos por incapacidad o discapacidad.";
            } else if(CFDI_cmb == 5) {
               CFDI_string = "D03 Gastos funerales.";
            } else if(CFDI_cmb == 6) {
               CFDI_string = "D04 Donativos.";
            } else if(CFDI_cmb == 7) {
               CFDI_string = "D05 Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).";
            } else if(CFDI_cmb == 8) {
               CFDI_string = "D06 Aportaciones voluntarias al SAR.";
            } else if(CFDI_cmb == 9) {
               CFDI_string = "D07 Primas por seguros de gastos médicos.";
            } else if(CFDI_cmb == 10) {
               CFDI_string = "D08 Gastos de transportación escolar obligatoria.";
            } else if(CFDI_cmb == 11) {
               CFDI_string = "D09 Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.";
            } else if(CFDI_cmb == 12) {
               CFDI_string = "D10 Pagos por servicios educativos (colegiaturas).";
            } else if(CFDI_cmb == 13) {
               CFDI_string = "G01 Adquisición de mercancias.";
            } else if(CFDI_cmb == 14) {
               CFDI_string = "G02 Devoluciones, descuentos o bonificaciones.";
            } else if(CFDI_cmb == 15) {
               CFDI_string = "G03 Gastos en general.";
            } else if(CFDI_cmb == 16) {
               CFDI_string = "I01 Construcciones.";
            } else if(CFDI_cmb == 17) {
               CFDI_string = "I02 Mobiliario y equipo de oficina por inversiones."; 
            } else if(CFDI_cmb == 18) {
               CFDI_string = "I03 Equipo de transporte.";
            } else if(CFDI_cmb == 19) {
               CFDI_string = "I04 Equipo de computo y accesorios.";
            } else if(CFDI_cmb == 20) {
               CFDI_string = "I05 Dados, troqueles, moldes, matrices y herramental.";
            } else if(CFDI_cmb == 21) {
               CFDI_string = "I06 Comunicaciones telefónicas.";
            } else if(CFDI_cmb == 22) {
               CFDI_string = "I07 Comunicaciones satelitales.";
            } else if(CFDI_cmb == 23) {
               CFDI_string = "I08 Otra maquinaria y equipo.";
            }
        
        
 
            if(metodoPago_cmb == 1) {
               metodoPago_string = "Ninguno";
            } else if(metodoPago_cmb == 2) {
               metodoPago_string = "Efectivo";
            } else if(metodoPago_cmb == 3) {
               metodoPago_string = "Transferencia";
            } else if(metodoPago_cmb == 4) {
               metodoPago_string = "Depósito";
            } else if(metodoPago_cmb == 5) {
               metodoPago_string = "Tarjeta de Crédito/Débito";
            }
        
           
           
           
       if (validacion == 0){
     
     try {
            
             Connection cn = Conexion.conectar();
             PreparedStatement pst = cn.prepareStatement(
                     "insert into facturacion values (?,?,?,?,?,?,?,?)");
             
             pst.setInt(1, 0);
             pst.setString(2, RFC);
             pst.setString(3, razonsocial);
             pst.setString(4, CFDI_string);
             pst.setString(5, metodoPago_string);
             pst.setString(6, MontoTotal);
             pst.setString(7, mail);
             pst.setString(8, user);
             
             pst.executeUpdate();
             cn.close();
             
             Limpiar();
  
             txt_RFC.setBackground(Color.green);
             txt_razonsocial.setBackground(Color.green);
             txt_mail.setBackground(Color.green);
      
             
             JOptionPane.showMessageDialog(null, "Registro exitoso.");
             this.dispose();
             
         } catch (SQLException e) {
             System.out.println("Error en registrar cliente." + e);
             JOptionPane.showMessageDialog(null, "ERROR al registrar cliente!!, contacte al administrador.");
         } 
     
         
       } else {
          JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
       }
       
    }//GEN-LAST:event_jButton1ActionPerformed
   
     
    private void txt_mailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mailActionPerformed

    private void txt_MontoTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MontoTotalKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();
        
        if(Character.isLetter(validar)){
           getToolkit().beep();
           evt.consume();
           
           JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
        
        }
            
            
            
            
    }//GEN-LAST:event_txt_MontoTotalKeyTyped

    private void txt_MontoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MontoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MontoTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datosfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datosfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datosfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datosfacturacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Datosfacturacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_CFDI;
    private javax.swing.JComboBox<String> cmb_metodoPago;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_MontoTotal;
    private javax.swing.JTextField txt_RFC;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_razonsocial;
    // End of variables declaration//GEN-END:variables

public void Limpiar() {
       txt_RFC.setText("");
       txt_razonsocial.setText("");
       txt_mail.setText("");
    }

}
