/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author raula
 */
public class Estudio extends javax.swing.JFrame {
int IDpaciente_update = 0;
String user = "", nom_paciente = "", NdeFolios="" , IDpaciente="";
private TextAutoCompleter ac;
public static int IDestudio = 0, IDEst;
  
    /**
     * Creates new form Estudio
     */
    public Estudio() {
        initComponents();
  
        user = Login.user;
     
        IDpaciente_update = GestionarPacientes.IDpaciente_update;
        
        
        
        
         setTitle("Registrar nuevo estudio para " + nom_paciente); 
        setSize(606, 200);
        setResizable(false);
        setLocationRelativeTo(null);
        
       
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
              try {
          
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
             "select * from pacientes where id_paciente = '" + IDpaciente_update + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()){
                setTitle("Registro del Paciente " + rs.getString("nombre_paciente") + " " + rs.getString("apellido_paciente") + " - Sesión de " + user);
                jLabel_Titulo.setText("Registro del Paciente " + rs.getString("nombre_paciente") + " " + rs.getString("apellido_paciente"));
                
         
               
                
            }
            cn.close();
             
        } catch (SQLException e) {
            System.err.println("Error al cargar usuario." + e);
            JOptionPane.showMessageDialog(
                null, "¡¡ERROR al cargar!!, contacte al administrador");
        }
        
        
        
        TextAutoCompleter textAutoAcomplter2 = new TextAutoCompleter(txt_nombredelestudio);
        textAutoAcomplter2.addItem("Carga viral HBV");
        textAutoAcomplter2.addItem("Carga viral HCV");
        textAutoAcomplter2.addItem("Carga viral VIH");
        textAutoAcomplter2.addItem("CD4 y CD8");
        textAutoAcomplter2.addItem("FTA-ABS");
        textAutoAcomplter2.addItem("HLA A, B,C DQ, DR (Baja resolución)");
        textAutoAcomplter2.addItem("Anticoagulante lúpico");
        textAutoAcomplter2.addItem("Antígeno de Von Willebrand");
        textAutoAcomplter2.addItem("Antígeno SARS CoV-2");
        textAutoAcomplter2.addItem("Dímero D");
        textAutoAcomplter2.addItem("BH 0 a 1 mes");
        textAutoAcomplter2.addItem("BH 2 a 6 meses");
        textAutoAcomplter2.addItem("BH 3 a 5 años");
        textAutoAcomplter2.addItem("BH 6 a 10 años");
        textAutoAcomplter2.addItem("BH 7 a 24 meses");
        textAutoAcomplter2.addItem("BH 11 a 15 años");
        textAutoAcomplter2.addItem("BH Femenino mas de 16 años");
        textAutoAcomplter2.addItem("BH Masculino mas de 16 años");
        textAutoAcomplter2.addItem("BH Neonato 0 a 1 día");
        textAutoAcomplter2.addItem("BH Neonato 1 a 4 días");
        textAutoAcomplter2.addItem("BH Neonato 4 a 7 días");
        textAutoAcomplter2.addItem("Grupo sanguíneo y Rh (Hemaglutinación)");
        textAutoAcomplter2.addItem("TP y TTP");
        textAutoAcomplter2.addItem("QS6 19 a 50 años");
        textAutoAcomplter2.setMode(0); // infijo
             
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Logo1.jpg"));
        return retValue;
    }
    public static String estudio = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt_nombredelestudio = new javax.swing.JTextField();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 95, -1, -1));

        txt_nombredelestudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombredelestudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombredelestudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombredelestudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombredelestudio.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txt_nombredelestudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombredelestudioActionPerformed(evt);
            }
        });
        txt_nombredelestudio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombredelestudioKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nombredelestudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 52, 330, -1));

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Registro del Paciente");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoUni.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
         try {
            Connection cn2 = Conexion.conectar();
            PreparedStatement pst2 = cn2.prepareStatement(
                   "SELECT MAX(NdeFolio) AS NdeFolio FROM estudios");
            ResultSet rs2 = pst2.executeQuery();
            
            if(rs2.next()) {
                
                NdeFolios = rs2.getString("NdeFolio");
                
            }
            
        } catch (SQLException e) {
           System.err.println("Error al consultar el numero del folio.");
        }
        try {
            Connection cn5 = Conexion.conectar();
            PreparedStatement pst5 = cn5.prepareStatement(
                   "select * from estudios where NdeFolio = '" + NdeFolios + "'");
            ResultSet rs5 = pst5.executeQuery();
            
            if(rs5.next()) {
                
                IDpaciente = rs5.getString("id_paciente");
                
            }
            
        } catch (SQLException e) {
           System.err.println("Error al consultar el IDpaciente del paciente.");
        }
    
        int Opciones;
        Opciones = JOptionPane.showConfirmDialog(this, "¿Te gustaria registrar el estudio con el mismo folio anterior de " + NdeFolios + " perteneciente al paciente con ID de: " + IDpaciente + "?");
        IDEst = Integer.parseInt(NdeFolios);
        if (Opciones == 1){
        IDEst++;}
        estudio = txt_nombredelestudio.getText();
        RegistrarEstudio registrarEstudio = new RegistrarEstudio();
        registrarEstudio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nombredelestudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombredelestudioActionPerformed

    }//GEN-LAST:event_txt_nombredelestudioActionPerformed

    private void txt_nombredelestudioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombredelestudioKeyReleased

    }//GEN-LAST:event_txt_nombredelestudioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_nombredelestudio;
    // End of variables declaration//GEN-END:variables
}
