/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.UIManager.getInt;
import javax.swing.WindowConstants;



/**
 *
 * @author raula
 */
public class InformacionEstudio extends javax.swing.JFrame {

int IDpaciente_update = 0, IDestudio = 0 ;
String user = "", nom_paciente = "";
public static int IEstudio = 0;
    /**
     * Creates new form Reporte_estudio
     */
    public InformacionEstudio() {
        initComponents();
        user = Login.user;
        IDestudio = Estudio_paciente.IDestudio;
        IDpaciente_update = GestionarPacientes.IDpaciente_update;
        
        try {
          Connection cn = Conexion.conectar();
          PreparedStatement pst = cn.prepareStatement(
                  "select nombre_paciente from pacientes where id_paciente = '" + IDpaciente_update + "'");
          ResultSet rs = pst.executeQuery();
          
          if(rs.next()){
              
            nom_paciente = rs.getString("nombre_paciente");
          }
          
        } catch (Exception e) {
            System.err.println("Error al consultar el nombre del paciente");
        }
        
        try {
          Connection cn = Conexion.conectar();
          PreparedStatement pst = cn.prepareStatement(
                  "select * from estudios where id_estudio = '" + IDestudio + "'");
          ResultSet rs = pst.executeQuery();
          
          if (rs.next()) {
              
               setTitle("Información del estudio " + rs.getString("nombre_estudio")  + " - Sesión de " + user);
                jLabel_Titulo.setText("Información del estudio " + rs.getString("nombre_estudio"));
              
              
            IEstudio =  rs.getInt("id_estudio"); 
            txt_NoFolio.setText(rs.getString("NdeFolio"));
            txt_claveEstudio.setText(rs.getString("clave_estudio"));
            txt_nombreEstudio.setText(rs.getString("nombre_estudio"));
            txt_tipodeMuestra.setText(rs.getString("tipo_muestra"));
            txt_diadeEntrega.setText(rs.getString("dia_entrega"));
            txt_costoEstudio.setText(rs.getString("costo_estudio"));
            jTextPane_indicaciones.setText(rs.getString("indicacion_estudio"));
            cmb_estatus.setSelectedItem(rs.getString("estatus"));
            txt_ultimaModificacion.setText(rs.getString("ultima_modificacion"));
            
            String dia = "", mes = "", annio = "";
            dia = rs.getString("dia_registrado");
            mes = rs.getString("mes_registrado");
            annio = rs.getString("año_registrado");
            txt_fechaRegistrado.setText(dia + "/" + mes + "/" + annio);
            
            
          }
          
          
        } catch (Exception e) {
         System.err.println("Error al consultar la información del estudio");
        }
        
        
   
        
        setSize(680, 700);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
    }

     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Logo1.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_NoFolio = new javax.swing.JLabel();
        txt_NoFolio = new javax.swing.JTextField();
        jLabel_claveestudio = new javax.swing.JLabel();
        txt_claveEstudio = new javax.swing.JTextField();
        jLabel_nombreestudio = new javax.swing.JLabel();
        txt_nombreEstudio = new javax.swing.JTextField();
        jLabel_tipodemuestra = new javax.swing.JLabel();
        txt_tipodeMuestra = new javax.swing.JTextField();
        jLabel_diadeentrega = new javax.swing.JLabel();
        txt_diadeEntrega = new javax.swing.JTextField();
        jLabel_diaregistrado = new javax.swing.JLabel();
        txt_fechaRegistrado = new javax.swing.JTextField();
        jLabel_costoEstudio = new javax.swing.JLabel();
        txt_costoEstudio = new javax.swing.JTextField();
        jLabel_indicaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_indicaciones = new javax.swing.JTextPane();
        jLabel_estatus = new javax.swing.JLabel();
        jButton_GenerarReporte = new javax.swing.JButton();
        cmb_estatus = new javax.swing.JComboBox<>();
        jButton_ActualizarEstudio = new javax.swing.JButton();
        jLabel_modificadoPor = new javax.swing.JLabel();
        txt_ultimaModificacion = new javax.swing.JTextField();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel_Titulo.setText("Información del estudio");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel_NoFolio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_NoFolio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NoFolio.setText("No. de folio:");
        getContentPane().add(jLabel_NoFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_NoFolio.setBackground(new java.awt.Color(153, 153, 255));
        txt_NoFolio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_NoFolio.setForeground(new java.awt.Color(255, 255, 255));
        txt_NoFolio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_NoFolio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_NoFolio.setEnabled(false);
        txt_NoFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NoFolioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NoFolio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 300, -1));

        jLabel_claveestudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_claveestudio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_claveestudio.setText("Clave del estudio");
        getContentPane().add(jLabel_claveestudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txt_claveEstudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_claveEstudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_claveEstudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_claveEstudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_claveEstudio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_claveEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 300, -1));

        jLabel_nombreestudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nombreestudio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreestudio.setText("Nombre del estudio");
        getContentPane().add(jLabel_nombreestudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_nombreEstudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombreEstudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombreEstudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombreEstudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombreEstudio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombreEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreEstudioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombreEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 300, -1));

        jLabel_tipodemuestra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_tipodemuestra.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tipodemuestra.setText("Tipo de muestra:");
        getContentPane().add(jLabel_tipodemuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txt_tipodeMuestra.setBackground(new java.awt.Color(153, 153, 255));
        txt_tipodeMuestra.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_tipodeMuestra.setForeground(new java.awt.Color(255, 255, 255));
        txt_tipodeMuestra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tipodeMuestra.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_tipodeMuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 300, -1));

        jLabel_diadeentrega.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_diadeentrega.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_diadeentrega.setText("Dia de entrega");
        getContentPane().add(jLabel_diadeentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        txt_diadeEntrega.setBackground(new java.awt.Color(153, 153, 255));
        txt_diadeEntrega.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_diadeEntrega.setForeground(new java.awt.Color(255, 255, 255));
        txt_diadeEntrega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_diadeEntrega.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_diadeEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 300, -1));

        jLabel_diaregistrado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_diaregistrado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_diaregistrado.setText("Fecha de registro:");
        getContentPane().add(jLabel_diaregistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        txt_fechaRegistrado.setBackground(new java.awt.Color(153, 153, 255));
        txt_fechaRegistrado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_fechaRegistrado.setForeground(new java.awt.Color(255, 255, 255));
        txt_fechaRegistrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fechaRegistrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_fechaRegistrado.setEnabled(false);
        txt_fechaRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaRegistradoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_fechaRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 300, -1));

        jLabel_costoEstudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_costoEstudio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_costoEstudio.setText("Costo del estudio:");
        getContentPane().add(jLabel_costoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        txt_costoEstudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_costoEstudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_costoEstudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_costoEstudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_costoEstudio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_costoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 300, -1));

        jLabel_indicaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_indicaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_indicaciones.setText("Indicaciones:");
        getContentPane().add(jLabel_indicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jScrollPane1.setViewportView(jTextPane_indicaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 630, 190));

        jLabel_estatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_estatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_estatus.setText("Estatus");
        getContentPane().add(jLabel_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 545, -1, -1));

        jButton_GenerarReporte.setBackground(new java.awt.Color(204, 51, 255));
        jButton_GenerarReporte.setText("Datos para reporte");
        jButton_GenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 250, -1));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso", "Entregado" }));
        cmb_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jButton_ActualizarEstudio.setText("Actualizar Infomación");
        jButton_ActualizarEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarEstudioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ActualizarEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 250, -1));

        jLabel_modificadoPor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_modificadoPor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_modificadoPor.setText("Última modificación");
        getContentPane().add(jLabel_modificadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 575, -1, -1));

        txt_ultimaModificacion.setBackground(new java.awt.Color(153, 153, 255));
        txt_ultimaModificacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_ultimaModificacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_ultimaModificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ultimaModificacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ultimaModificacion.setEnabled(false);
        txt_ultimaModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ultimaModificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ultimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 595, 210, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoUni.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreEstudioActionPerformed

    private void jButton_GenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GenerarReporteActionPerformed


        
    
      
     String nombre_estudio = "Carga viral HBV", nombre_estudio1 = "Carga viral HCV", nombre_estudio2 = "Carga viral VIH", nombre_estudio3 = "CD4 y CD8", nombre_estudio4 = "FTA-ABS", nombre_estudio5 = "HLA A, B,C DQ, DR (Baja resolución)",
             nombre_estudio6 = "Anticoagulante lúpico", nombre_estudio7 = "Antígeno de Von Willebrand", nombre_estudio8 = "BH 0 a 1 mes", nombre_estudio9 = "BH 2 a 6 meses",
             nombre_estudio10 = "BH 3 a 5 años", nombre_estudio11 = "BH 6 a 10 años", nombre_estudio12 = "BH 7 a 24 meses", nombre_estudio13 = "BH 11 a 15 años",
             nombre_estudio14 = "BH Femenino mas de 16 años", nombre_estudio15 = "BH Masculino mas de 16 años", nombre_estudio16 = "BH Neonato 0 a 1 día", nombre_estudio17 = "BH Neonato 1 a 4 días",
             nombre_estudio18 = "BH Neonato 4 a 7 días", 
             nombre_estudio20 = "Grupo sanguíneo y Rh (Hemaglutinación)", nombre_estudio21 = "Antígeno SARS CoV-2",
             nombre_estudio22 = "TP y TTP", nombre_estudio23 = "Dímero D", nombre_estudio24 = "QS6 19 a 50 años";
      
              
        if(txt_nombreEstudio.getText().equals(nombre_estudio)) {
          CargaviralHBV cargaviralHBV = new CargaviralHBV();
          cargaviralHBV.setVisible(true);
        }
        
        if(txt_nombreEstudio.getText().equals(nombre_estudio1)) {
          CargaviralHCV cargaviralHCV = new CargaviralHCV();
          cargaviralHCV.setVisible(true);
        } 
        
        if(txt_nombreEstudio.getText().equals(nombre_estudio2)) {
          CargaviralVIH cargaviralVIH = new CargaviralVIH();
          cargaviralVIH.setVisible(true);
        }
        if(txt_nombreEstudio.getText().equals(nombre_estudio3)) {
          CD4yCD8 cD4yCD8 = new CD4yCD8();
          cD4yCD8.setVisible(true);
        } 
         if(txt_nombreEstudio.getText().equals(nombre_estudio4)) {
          FTA_ABS fTA_ABS = new FTA_ABS();
          fTA_ABS.setVisible(true);
        } 
         if(txt_nombreEstudio.getText().equals(nombre_estudio5)) {
          HLA_A_B_C_DQ_DR hLA_A_B_C_DQ_DR = new HLA_A_B_C_DQ_DR();
          hLA_A_B_C_DQ_DR.setVisible(true);
        } 
        if(txt_nombreEstudio.getText().equals(nombre_estudio6)) {
          Anticoagulantelúpico anticoagulantelúpico = new Anticoagulantelúpico();
          anticoagulantelúpico.setVisible(true);
        }
        if(txt_nombreEstudio.getText().equals(nombre_estudio7)) {
          AntígenodeVonWillebrand antígenodeVonWillebrand = new AntígenodeVonWillebrand();
          antígenodeVonWillebrand.setVisible(true);
        }
        if(txt_nombreEstudio.getText().equals(nombre_estudio8)) {
          BH0a1mes1 bH0a1mes1 = new BH0a1mes1();
          bH0a1mes1.setVisible(true);
        }
        if(txt_nombreEstudio.getText().equals(nombre_estudio9)) {
          BH2a6meses bH2a6meses = new BH2a6meses();
          bH2a6meses.setVisible(true);
        }
         if(txt_nombreEstudio.getText().equals(nombre_estudio10)) {
          BH3a5años bH3a5años = new BH3a5años();
          bH3a5años.setVisible(true);
        }     
         if(txt_nombreEstudio.getText().equals(nombre_estudio11)) {
          BH6a10años bH6a10años = new BH6a10años();
          bH6a10años.setVisible(true);
        }  
        if(txt_nombreEstudio.getText().equals(nombre_estudio12)) {
          BH7a24meses bH7a24meses = new BH7a24meses();
          bH7a24meses.setVisible(true);
        } 
        if(txt_nombreEstudio.getText().equals(nombre_estudio13)) {
          BH11a15años bH11a15años = new BH11a15años();
          bH11a15años.setVisible(true);
        } 
        if(txt_nombreEstudio.getText().equals(nombre_estudio14)) {
          BHFemeninomasde16años bHFemeninomasde16años = new BHFemeninomasde16años();
          bHFemeninomasde16años.setVisible(true);
        }  
         if(txt_nombreEstudio.getText().equals(nombre_estudio15)) {
          BHMasculinomasde16años bHMasculinomasde16años = new BHMasculinomasde16años();
          bHMasculinomasde16años.setVisible(true);
        } 
         if(txt_nombreEstudio.getText().equals(nombre_estudio16)) {
          BHNeonato0a1día bHNeonato0a1día = new BHNeonato0a1día();
          bHNeonato0a1día.setVisible(true);
        } 
           if(txt_nombreEstudio.getText().equals(nombre_estudio17)) {
          BHNeonato1a4días bHNeonato1a4días = new BHNeonato1a4días();
          bHNeonato1a4días.setVisible(true);
        }
            if(txt_nombreEstudio.getText().equals(nombre_estudio18)) {
          BHNeonato4a7días bHNeonato4a7días = new BHNeonato4a7días();
          bHNeonato4a7días.setVisible(true);
        } 
       
            if(txt_nombreEstudio.getText().equals(nombre_estudio20)) {
          GruposanguíneoyRh gruposanguíneo = new GruposanguíneoyRh();
          gruposanguíneo.setVisible(true);
        }
            if(txt_nombreEstudio.getText().equals(nombre_estudio21)) {
          AntígenoSARSCoV2 antígenoSARSCoV2 = new AntígenoSARSCoV2();
          antígenoSARSCoV2.setVisible(true);
        }
            if(txt_nombreEstudio.getText().equals(nombre_estudio22)) {
          TPyTTP TpyTTp = new TPyTTP();
          TpyTTp.setVisible(true);
        }     
           if(txt_nombreEstudio.getText().equals(nombre_estudio23)) {
          DimeroD dimeroD = new DimeroD();
          dimeroD.setVisible(true);
        } 
           if(txt_nombreEstudio.getText().equals(nombre_estudio24)) {
          QS619a50años qS619a50años = new QS619a50años();
          qS619a50años.setVisible(true);
        }         
         
    }//GEN-LAST:event_jButton_GenerarReporteActionPerformed

    private void jButton_ActualizarEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarEstudioActionPerformed
        
        int validacion = 0;
        String clave_estudio, nombre_estudio, tipo_muestra, dia_entrega, fecha_registrado, costo_estudio, estatus,indicaciones;
        
        clave_estudio = txt_claveEstudio.getText().trim();
        nombre_estudio = txt_nombreEstudio.getText().trim();
        tipo_muestra = txt_tipodeMuestra.getText().trim();
        dia_entrega = txt_diadeEntrega.getText().trim();
        fecha_registrado = txt_fechaRegistrado.getText().trim();
        costo_estudio = txt_costoEstudio.getText().trim();
        
        estatus = cmb_estatus.getSelectedItem().toString();
        
        indicaciones = jTextPane_indicaciones.getText();
        
        if (clave_estudio.equals("")) {
          txt_claveEstudio.setBackground(Color.red);
          validacion++;
        }
        if (nombre_estudio.equals("")) {
          txt_nombreEstudio.setBackground(Color.red);
          validacion++;
        }
        if (tipo_muestra.equals("")) {
          txt_tipodeMuestra.setBackground(Color.red);
          validacion++;
        }
        if (dia_entrega.equals("")) {
          txt_diadeEntrega.setBackground(Color.red);
          validacion++;
        }
        if (fecha_registrado.equals("")) {
          txt_fechaRegistrado.setBackground(Color.red);
          validacion++;
        }
        if (costo_estudio.equals("")) {
          txt_costoEstudio.setBackground(Color.red);
          validacion++;
        }
        if (indicaciones.equals("")) {
          jTextPane_indicaciones.setText("Sin indicaciones");
        
        }
        
        if (validacion == 0) {
          
            try{
               Connection cn = Conexion.conectar();
               PreparedStatement pst = cn.prepareStatement(
                       "update estudios set clave_estudio=?, nombre_estudio=?, tipo_muestra=?, dia_entrega=?, costo_estudio=?,estatus=?, indicacion_estudio=?,ultima_modificacion=? " 
                   + "where id_estudio = '" + IDestudio + "'");
               
               pst.setString(1, clave_estudio);
               pst.setString(2, nombre_estudio);
               pst.setString(3, tipo_muestra);
               pst.setString(4, dia_entrega);
               pst.setString(5, costo_estudio);
               pst.setString(6, estatus);
               pst.setString(7, indicaciones);
               pst.setString(8, user);
               
               pst.executeUpdate();
               cn.close();
               
               Limpiar();
               
               txt_claveEstudio.setBackground(Color.green);
               txt_nombreEstudio.setBackground(Color.green);
               txt_tipodeMuestra.setBackground(Color.green);
               txt_diadeEntrega.setBackground(Color.green);
               txt_fechaRegistrado.setBackground(Color.green);
               txt_costoEstudio.setBackground(Color.green);
               txt_ultimaModificacion.setText(user);
              
               JOptionPane.showMessageDialog(null, "Actualizacion correcta.");
               
               this.dispose();
               
            } catch (SQLException e){
               System.err.println("Error en actualizar estudio" + e);
               JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar paciente!!, contacte al programador.");
            }
    
        } else {
        }
        
        
        
    }//GEN-LAST:event_jButton_ActualizarEstudioActionPerformed

    private void txt_ultimaModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ultimaModificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ultimaModificacionActionPerformed

    private void cmb_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estatusActionPerformed

    private void txt_NoFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NoFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NoFolioActionPerformed

    private void txt_fechaRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaRegistradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_fechaRegistradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionEstudio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionEstudio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JButton jButton_ActualizarEstudio;
    private javax.swing.JButton jButton_GenerarReporte;
    private javax.swing.JLabel jLabel_NoFolio;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_claveestudio;
    private javax.swing.JLabel jLabel_costoEstudio;
    private javax.swing.JLabel jLabel_diadeentrega;
    private javax.swing.JLabel jLabel_diaregistrado;
    private javax.swing.JLabel jLabel_estatus;
    private javax.swing.JLabel jLabel_indicaciones;
    private javax.swing.JLabel jLabel_modificadoPor;
    private javax.swing.JLabel jLabel_nombreestudio;
    private javax.swing.JLabel jLabel_tipodemuestra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_indicaciones;
    private javax.swing.JTextField txt_NoFolio;
    private javax.swing.JTextField txt_claveEstudio;
    private javax.swing.JTextField txt_costoEstudio;
    private javax.swing.JTextField txt_diadeEntrega;
    private javax.swing.JTextField txt_fechaRegistrado;
    private javax.swing.JTextField txt_nombreEstudio;
    private javax.swing.JTextField txt_tipodeMuestra;
    private javax.swing.JTextField txt_ultimaModificacion;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
     txt_claveEstudio.setText("");
     txt_nombreEstudio.setText("");
     txt_tipodeMuestra.setText("");
     txt_diadeEntrega.setText("");
     txt_fechaRegistrado.setText("");
     txt_costoEstudio.setText("");
     jTextPane_indicaciones.setText("");
    
    
    }


}
