/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import com.mxrck.autocompleter.TextAutoCompleter;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author raula
 */
public class NfolioRecibo extends javax.swing.JFrame {
int IDpaciente_update = 0;
String user = "", nom_paciente = "", NdeFolios="" , IDpaciente="";
private TextAutoCompleter ac;
public static String IDEst = "";
  
    /**
     * Creates new form Estudio
     */
    public NfolioRecibo() {
        initComponents();
  
        user = Login.user;
     
        IDpaciente_update = GestionarPacientes.IDpaciente_update;
        
        
        
        
         setTitle("Generar recibo para " + nom_paciente); 
        setSize(342, 198);
        setResizable(false);
        setLocationRelativeTo(null);
        
       
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
              try {
          
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
             "select * from pacientes where id_paciente = '" + IDpaciente_update + "'");
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()){
                setTitle("N. de folio para recibo " + rs.getString("nombre_paciente") + " " + rs.getString("apellido_paciente") + " - Sesión de " + user);
      
            }
            cn.close();
             
        } catch (SQLException e) {
            System.err.println("Error al cargar usuario." + e);
            JOptionPane.showMessageDialog(
                null, "¡¡ERROR al cargar!!, contacte al administrador");
        }
             
    }
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Logo1.jpg"));
        return retValue;
    }
    public static String estudio = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt_nombredelestudio = new javax.swing.JTextField();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        txt_nombredelestudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombredelestudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombredelestudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombredelestudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombredelestudio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombredelestudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombredelestudioActionPerformed(evt);
            }
        });
        txt_nombredelestudio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombredelestudioKeyReleased(evt);
            }
        });
        getContentPane().add(txt_nombredelestudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 230, -1));

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("N. de folio para recibo");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoUni.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
IDEst = txt_nombredelestudio.getText();
try{
           Connection cn = Conexion.conectar();
           PreparedStatement pst = cn.prepareStatement(
             "select ID_Ndefolio from Recibos where ID_Ndefolio = '" + IDEst + "'");
           ResultSet rs = pst.executeQuery();
        
           if (rs.next()) {
               txt_nombredelestudio.setBackground(Color.red);
               JOptionPane.showMessageDialog(null, "Numero de folio ya registrado.");
               cn.close();
           } else { 
        GenerarRecibo generarRecibo = new GenerarRecibo();
        generarRecibo.setVisible(true);
        dispose();
} }catch (Exception e){
            System.err.println("Error en validar folio." + e);
            JOptionPane.showMessageDialog(null, "¡¡ERROR al comparar folio disponible!!, contacte al programador.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_nombredelestudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombredelestudioActionPerformed

    }//GEN-LAST:event_txt_nombredelestudioActionPerformed

    private void txt_nombredelestudioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombredelestudioKeyReleased

    }//GEN-LAST:event_txt_nombredelestudioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NfolioRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NfolioRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NfolioRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NfolioRecibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NfolioRecibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JTextField txt_nombredelestudio;
    // End of variables declaration//GEN-END:variables
}
