/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author raula
 */
public class RegistrarPacientes extends javax.swing.JFrame {

    String user;
 
    /**
     * Creates new form RegistrarPacientes
     */
    public RegistrarPacientes() {
        initComponents();
        user = Login.user;

        
        setTitle("Registrar nuevo paciente - Sesión de " + user);
        setSize(530, 600);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
     
    }

       @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Logo1.jpg"));
      
       return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_empresa = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        cmb_sexo = new javax.swing.JComboBox<>();
        txt_mail = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        txt_nombremedico = new javax.swing.JTextField();
        txt_telefonom = new javax.swing.JTextField();
        txt_mailmedico = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        jDateChooser_fnacimiento = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel_footer = new javax.swing.JLabel();
        jCheckBox_facturar = new javax.swing.JCheckBox();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de pacientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Em@il:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrar Paciente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 430, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Apellidos:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Empresa:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Fecha de nacimiento:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Sexo:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Médico solicitante:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Teléfono del médico:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Correo del médico:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Edad:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txt_empresa.setBackground(new java.awt.Color(153, 153, 255));
        txt_empresa.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_empresa.setForeground(new java.awt.Color(255, 255, 255));
        txt_empresa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_empresa.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, -1));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, -1));

        txt_apellido.setBackground(new java.awt.Color(153, 153, 255));
        txt_apellido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_apellido.setForeground(new java.awt.Color(255, 255, 255));
        txt_apellido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_apellido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, -1));

        cmb_sexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        getContentPane().add(cmb_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, -1));

        txt_mail.setBackground(new java.awt.Color(153, 153, 255));
        txt_mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_mail.setForeground(new java.awt.Color(255, 255, 255));
        txt_mail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 210, -1));

        txt_telefono.setBackground(new java.awt.Color(153, 153, 255));
        txt_telefono.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefono.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 210, -1));

        txt_direccion.setBackground(new java.awt.Color(153, 153, 255));
        txt_direccion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_direccion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 210, -1));

        txt_nombremedico.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombremedico.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombremedico.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombremedico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombremedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_nombremedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 210, -1));

        txt_telefonom.setBackground(new java.awt.Color(153, 153, 255));
        txt_telefonom.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_telefonom.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefonom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_telefonom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_telefonom, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 210, -1));

        txt_mailmedico.setBackground(new java.awt.Color(153, 153, 255));
        txt_mailmedico.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_mailmedico.setForeground(new java.awt.Color(255, 255, 255));
        txt_mailmedico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_mailmedico.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_mailmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 210, -1));

        txt_edad.setBackground(new java.awt.Color(153, 153, 255));
        txt_edad.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_edad.setForeground(new java.awt.Color(255, 255, 255));
        txt_edad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_edad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, -1));
        getContentPane().add(jDateChooser_fnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/AñadirUser.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 120, 100));

        jLabel_footer.setText("Creado por DGSystem ®");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, -1, -1));

        jCheckBox_facturar.setText("Facturar");
        jCheckBox_facturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_facturarActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_facturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoUni.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       int sexo_cmb, validacion = 0;
       
  SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
       
       String empresa, nombre, apellido, edad, fnacimiento, sexo_string = "", mail, telefono, direccion, nombremedico, telefonom, mailmedico, facturar ="", RFC = "", razonsocial = "", mailfacturacion, CFDI_cmb = "", metodoPago_cmb = "", MontoTotal = "";
      
       empresa = txt_empresa.getText().trim();
       nombre = txt_nombre.getText().trim();
       apellido = txt_apellido.getText().trim();
       edad = txt_edad.getText().trim();
       fnacimiento = dFormat.format(jDateChooser_fnacimiento.getDate());
       sexo_cmb = cmb_sexo.getSelectedIndex() + 1;
       mail = txt_mail.getText().trim();
       telefono = txt_telefono.getText().trim();
       direccion = txt_direccion.getText().trim();
       nombremedico = txt_nombremedico.getText().trim();
       telefonom = txt_telefonom.getText().trim();
       mailmedico = txt_mailmedico.getText().trim();
       mailfacturacion = "";
       CFDI_cmb = "";
       metodoPago_cmb = "";
       MontoTotal = "";
       facturar = "";
       RFC = "";
       razonsocial = "";
       

               
        if(empresa.equals("")) {
           txt_empresa.setBackground(Color.red);
           validacion++;     
       }
       if(nombre.equals("")) {
           txt_nombre.setBackground(Color.red);
           validacion++;     
       }
       if(apellido.equals("")) {
           txt_apellido.setBackground(Color.red);
           validacion++;     
       }
       if(edad.equals("")) {
           txt_edad.setBackground(Color.red);
           validacion++;     
       }
        if(fnacimiento.equals("")) {
           jDateChooser_fnacimiento.setBackground(Color.red);
           validacion++;     
       }
       if(mail.equals("")) {
           txt_mail.setBackground(Color.red);
           validacion++;     
       }
       if(telefono.equals("")) {
           txt_telefono.setBackground(Color.red);
           validacion++;     
       }
       if(direccion.equals("")) {
           txt_direccion.setBackground(Color.red);
           validacion++;     
       }
         if(nombremedico.equals("")) {
           txt_nombremedico.setBackground(Color.red);
           validacion++;     
       }
            if(telefonom.equals("")) {
           txt_telefonom.setBackground(Color.red);
           validacion++;     
       }
           if(mailmedico.equals("")) {
           txt_mailmedico.setBackground(Color.red);
           validacion++;     
       }    
            
       if (validacion == 0){
       
           if(sexo_cmb == 1) {
               sexo_string = "Masculino";
            } else if(sexo_cmb == 2) {
               sexo_string = "Femenino";
            }
           
        if (jCheckBox_facturar.isSelected()) {
            facturar = "Si";
             
        }   
        
        if (facturar.equals("")) {
            facturar = "No";
            RFC = "Ninguno";
            razonsocial = "Ninguno"; 
            CFDI_cmb = "Ninguno";
            metodoPago_cmb = "Ninguno";
            MontoTotal = "Ninguno";
            mailfacturacion = "Ninguno";
       
       
       if (validacion == 0){
     
     try {
            
             Connection cn1 = Conexion.conectar();
             PreparedStatement pst1 = cn1.prepareStatement(
                     "insert into facturacion values (?,?,?,?,?,?,?,?)");
             
             pst1.setInt(1, 0);
             pst1.setString(2, RFC);
             pst1.setString(3, razonsocial);
             pst1.setString(4, CFDI_cmb);
             pst1.setString(5, metodoPago_cmb);
             pst1.setString(6, MontoTotal);
             pst1.setString(7, mailfacturacion);
             pst1.setString(8, user);
             
             pst1.executeUpdate();
             cn1.close();
             
  

             
         } catch (SQLException e) {
          
         } 
     

       
    }                    
            
        }
        
         try {
            
             Connection cn = Conexion.conectar();
             PreparedStatement pst = cn.prepareStatement(
                     "insert into pacientes values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
             
             pst.setInt(1, 0);
             pst.setString(2, empresa);
             pst.setString(3, nombre);
             pst.setString(4, apellido);
             pst.setString(5, edad);
             pst.setString(6, fnacimiento);
             pst.setString(7, sexo_string);
             pst.setString(8, mail);
             pst.setString(9, telefono);
             pst.setString(10, direccion);
             pst.setString(11, nombremedico);
             pst.setString(12, telefonom);
             pst.setString(13, mailmedico);
             pst.setString(14, facturar);
             pst.setString(15, user);
             
             pst.executeUpdate();
             cn.close();
             
             Limpiar();
             
             txt_empresa.setBackground(Color.green);
             txt_nombre.setBackground(Color.green);
             txt_apellido.setBackground(Color.green);
             txt_edad.setBackground(Color.green);
             jDateChooser_fnacimiento.setBackground(Color.green);
             txt_mail.setBackground(Color.green);
             txt_telefono.setBackground(Color.green);
             txt_direccion.setBackground(Color.green);
             txt_nombremedico.setBackground(Color.green);
             txt_telefonom.setBackground(Color.green);
             txt_mailmedico.setBackground(Color.green);
             
             JOptionPane.showMessageDialog(null, "Registro exitoso.");
             this.dispose();
             
         } catch (SQLException e) {
             System.out.println("Error en registrar cliente." + e);
             JOptionPane.showMessageDialog(null, "ERROR al registrar cliente!!, contacte al administrador.");
         } 
           
       } else {
          JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
       }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox_facturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_facturarActionPerformed
        // TODO add your handling code here:
        if (jCheckBox_facturar.isSelected()) {
            Datosfacturacion datosfacturacion = new Datosfacturacion();
            datosfacturacion.setVisible(true);
    
        }
    }//GEN-LAST:event_jCheckBox_facturarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox_facturar;
    private com.toedter.calendar.JDateChooser jDateChooser_fnacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_empresa;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_mailmedico;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombremedico;
    private javax.swing.JTextField txt_telefono;
    private javax.swing.JTextField txt_telefonom;
    // End of variables declaration//GEN-END:variables
    
    public void Limpiar() {
       txt_empresa.setText("");
       txt_nombre.setText("");
       txt_apellido.setText("");
       txt_edad.setText("");
       txt_mail.setText("");
       txt_telefono.setText("");
       txt_direccion.setText("");
       txt_nombremedico.setText("");
       txt_telefonom.setText("");
       txt_mailmedico.setText("");
    }
}
