/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;



/**
 *
 * @author raula
 */
public class RegistroE extends javax.swing.JFrame {

int IDpaciente_update = 0, IDestudio = 0;
String user = "", nom_paciente = "";
    /**
     * Creates new form Reporte_estudio
     */
    public RegistroE() {
        initComponents();
        user = Login.user;
        IDestudio = Informacion_paciente.IDestudio;
        IDpaciente_update = GestionarPacientes.IDpaciente_update;
        
        try {
          Connection cn = Conexion.conectar();
          PreparedStatement pst = cn.prepareStatement(
                  "select nombre_paciente from pacientes where id_paciente = '" + IDpaciente_update + "'");
          ResultSet rs = pst.executeQuery();
          
          if(rs.next()){
            nom_paciente = rs.getString("nombre_paciente");
          }
          
        } catch (Exception e) {
            System.err.println("Error al consultar el nombre del paciente");
        }
        
        try {
          Connection cn = Conexion.conectar();
          PreparedStatement pst = cn.prepareStatement(
                  "select * from estudios where id_estudio = '" + IDestudio + "'");
          ResultSet rs = pst.executeQuery();
          
          if (rs.next()) {
            txt_claveEstudio.setText(rs.getString("clave_estudio"));
            txt_nombreEstudio.setText(rs.getString("nombre_estudio"));
            txt_tipodeMuestra.setText(rs.getString("tipo_muestra"));
            txt_diadeEntrega.setText(rs.getString("dia_entrega"));
            txt_costoEstudio.setText(rs.getString("costo_estudio"));
            jTextPane_indicaciones.setText(rs.getString("indicacion_estudio"));
            cmb_estatus.setSelectedItem(rs.getString("estatus"));
            txt_ultimaModificacion.setText(rs.getString("ultima_modificacion"));
            
            String dia = "", mes = "", annio = "";
            dia = rs.getString("dia_registrado");
            mes = rs.getString("mes_registrado");
            annio = rs.getString("año_registrado");
            txt_fechaRegistrado.setText(dia + "/" + mes + "/" + annio);
            
            
          }
          
          
        } catch (Exception e) {
         System.err.println("Error al consultar la información del estudio");
        }
        
        
   
        
        setSize(540, 700);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
   
    }

     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Logo1.jpg"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_claveestudio = new javax.swing.JLabel();
        txt_claveEstudio = new javax.swing.JTextField();
        jLabel_nombreestudio = new javax.swing.JLabel();
        txt_nombreEstudio = new javax.swing.JTextField();
        jLabel_tipodemuestra = new javax.swing.JLabel();
        txt_tipodeMuestra = new javax.swing.JTextField();
        jLabel_diadeentrega = new javax.swing.JLabel();
        txt_diadeEntrega = new javax.swing.JTextField();
        jLabel_diaregistrado = new javax.swing.JLabel();
        txt_fechaRegistrado = new javax.swing.JTextField();
        jLabel_costoEstudio = new javax.swing.JLabel();
        txt_costoEstudio = new javax.swing.JTextField();
        jLabel_indicaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane_indicaciones = new javax.swing.JTextPane();
        jLabel_estatus = new javax.swing.JLabel();
        jButton_GenerarReporte = new javax.swing.JButton();
        cmb_estatus = new javax.swing.JComboBox<>();
        jButton_ActualizarEstudio = new javax.swing.JButton();
        jLabel_modificadoPor = new javax.swing.JLabel();
        txt_ultimaModificacion = new javax.swing.JTextField();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Información del estudio");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel_claveestudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_claveestudio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_claveestudio.setText("Clave del estudio");
        getContentPane().add(jLabel_claveestudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txt_claveEstudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_claveEstudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_claveEstudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_claveEstudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_claveEstudio.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_claveEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 210, -1));

        jLabel_nombreestudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_nombreestudio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreestudio.setText("Nombre del estudio");
        getContentPane().add(jLabel_nombreestudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        txt_nombreEstudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombreEstudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombreEstudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombreEstudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombreEstudio.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txt_nombreEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreEstudioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_nombreEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 210, -1));

        jLabel_tipodemuestra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_tipodemuestra.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tipodemuestra.setText("Tipo de muestra:");
        getContentPane().add(jLabel_tipodemuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txt_tipodeMuestra.setBackground(new java.awt.Color(153, 153, 255));
        txt_tipodeMuestra.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_tipodeMuestra.setForeground(new java.awt.Color(255, 255, 255));
        txt_tipodeMuestra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_tipodeMuestra.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_tipodeMuestra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, -1));

        jLabel_diadeentrega.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_diadeentrega.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_diadeentrega.setText("Dia de entrega");
        getContentPane().add(jLabel_diadeentrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        txt_diadeEntrega.setBackground(new java.awt.Color(153, 153, 255));
        txt_diadeEntrega.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_diadeEntrega.setForeground(new java.awt.Color(255, 255, 255));
        txt_diadeEntrega.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_diadeEntrega.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_diadeEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, -1));

        jLabel_diaregistrado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_diaregistrado.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_diaregistrado.setText("Fecha de registro:");
        getContentPane().add(jLabel_diaregistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        txt_fechaRegistrado.setBackground(new java.awt.Color(153, 153, 255));
        txt_fechaRegistrado.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_fechaRegistrado.setForeground(new java.awt.Color(255, 255, 255));
        txt_fechaRegistrado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fechaRegistrado.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txt_fechaRegistrado.setEnabled(false);
        getContentPane().add(txt_fechaRegistrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 210, -1));

        jLabel_costoEstudio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_costoEstudio.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_costoEstudio.setText("Costo del estudio:");
        getContentPane().add(jLabel_costoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        txt_costoEstudio.setBackground(new java.awt.Color(153, 153, 255));
        txt_costoEstudio.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_costoEstudio.setForeground(new java.awt.Color(255, 255, 255));
        txt_costoEstudio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_costoEstudio.setBorder(new javax.swing.border.SoftBevelBorder(0));
        getContentPane().add(txt_costoEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 210, -1));

        jLabel_indicaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_indicaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_indicaciones.setText("Observaciones:");
        getContentPane().add(jLabel_indicaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jScrollPane1.setViewportView(jTextPane_indicaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 490, 190));

        jLabel_estatus.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_estatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_estatus.setText("Estatus");
        getContentPane().add(jLabel_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 545, -1, -1));

        jButton_GenerarReporte.setBackground(new java.awt.Color(204, 51, 255));
        jButton_GenerarReporte.setText("Datos para reporte");
        jButton_GenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GenerarReporteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 580, 160, -1));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En proceso", "Entregado" }));
        cmb_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jButton_ActualizarEstudio.setText("Actualizar Infomación");
        jButton_ActualizarEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarEstudioActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ActualizarEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 540, 160, -1));

        jLabel_modificadoPor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_modificadoPor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_modificadoPor.setText("Última modificación");
        getContentPane().add(jLabel_modificadoPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 575, -1, -1));

        txt_ultimaModificacion.setBackground(new java.awt.Color(153, 153, 255));
        txt_ultimaModificacion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_ultimaModificacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_ultimaModificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ultimaModificacion.setBorder(new javax.swing.border.SoftBevelBorder(0));
        txt_ultimaModificacion.setEnabled(false);
        txt_ultimaModificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ultimaModificacionActionPerformed(evt);
            }
        });
        getContentPane().add(txt_ultimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 595, 210, -1));

        jLabel_Wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/FondoUni.png"))); // NOI18N
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreEstudioActionPerformed

    private void jButton_GenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GenerarReporteActionPerformed

  
        
    
      
     String nombre_estudio = "Carga viral HBV", nombre_estudio1 = "Carga viral HCV", nombre_estudio2 = "Carga viral VIH", nombre_estudio3 = "CD4 y CD8", nombre_estudio4 = "FTA-ABS", nombre_estudio5 = "HLA A, B,C DQ, DR (Baja resolución)";
      
              
        if(txt_nombreEstudio.getText().equals(nombre_estudio)) {
          CargaviralHBV cargaviralHBV = new CargaviralHBV();
          cargaviralHBV.setVisible(true);
        }
        
        if(txt_nombreEstudio.getText().equals(nombre_estudio1)) {
          CargaviralHCV cargaviralHCV = new CargaviralHCV();
          cargaviralHCV.setVisible(true);
        } 
        
        if(txt_nombreEstudio.getText().equals(nombre_estudio2)) {
          CargaviralVIH cargaviralVIH = new CargaviralVIH();
          cargaviralVIH.setVisible(true);
        }
        if(txt_nombreEstudio.getText().equals(nombre_estudio3)) {
          CD4yCD8 cD4yCD8 = new CD4yCD8();
          cD4yCD8.setVisible(true);
        } 
         if(txt_nombreEstudio.getText().equals(nombre_estudio4)) {
          FTA_ABS fTA_ABS = new FTA_ABS();
          fTA_ABS.setVisible(true);
        } 
         if(txt_nombreEstudio.getText().equals(nombre_estudio5)) {
          HLA_A_B_C_DQ_DR hLA_A_B_C_DQ_DR = new HLA_A_B_C_DQ_DR();
          hLA_A_B_C_DQ_DR.setVisible(true);
        } 
        
        
        
        
             
             
    }//GEN-LAST:event_jButton_GenerarReporteActionPerformed

    private void jButton_ActualizarEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarEstudioActionPerformed
        
        int validacion = 0;
        String clave_estudio, nombre_estudio, tipo_muestra, dia_entrega, fecha_registrado, costo_estudio, estatus,indicaciones;
        
        clave_estudio = txt_claveEstudio.getText().trim();
        nombre_estudio = txt_nombreEstudio.getText().trim();
        tipo_muestra = txt_tipodeMuestra.getText().trim();
        dia_entrega = txt_diadeEntrega.getText().trim();
        fecha_registrado = txt_fechaRegistrado.getText().trim();
        costo_estudio = txt_costoEstudio.getText().trim();
        
        estatus = cmb_estatus.getSelectedItem().toString();
        
        indicaciones = jTextPane_indicaciones.getText();
        
        if (clave_estudio.equals("")) {
          txt_claveEstudio.setBackground(Color.red);
          validacion++;
        }
        if (nombre_estudio.equals("")) {
          txt_nombreEstudio.setBackground(Color.red);
          validacion++;
        }
        if (tipo_muestra.equals("")) {
          txt_tipodeMuestra.setBackground(Color.red);
          validacion++;
        }
        if (dia_entrega.equals("")) {
          txt_diadeEntrega.setBackground(Color.red);
          validacion++;
        }
        if (fecha_registrado.equals("")) {
          txt_fechaRegistrado.setBackground(Color.red);
          validacion++;
        }
        if (costo_estudio.equals("")) {
          txt_costoEstudio.setBackground(Color.red);
          validacion++;
        }
        if (indicaciones.equals("")) {
          jTextPane_indicaciones.setText("Sin indicaciones");
        
        }
        
        if (validacion == 0) {
          
            try{
               Connection cn = Conexion.conectar();
               PreparedStatement pst = cn.prepareStatement(
                       "update estudios set clave_estudio=?, nombre_estudio=?, tipo_muestra=?, dia_entrega=?, costo_estudio=?,estatus=?, indicacion_estudio=?,ultima_modificacion=? " 
                   + "where id_estudio = '" + IDestudio + "'");
               
               pst.setString(1, clave_estudio);
               pst.setString(2, nombre_estudio);
               pst.setString(3, tipo_muestra);
               pst.setString(4, dia_entrega);
               pst.setString(5, costo_estudio);
               pst.setString(6, estatus);
               pst.setString(7, indicaciones);
               pst.setString(8, user);
               
               pst.executeUpdate();
               cn.close();
               
               Limpiar();
               
               txt_claveEstudio.setBackground(Color.green);
               txt_nombreEstudio.setBackground(Color.green);
               txt_tipodeMuestra.setBackground(Color.green);
               txt_diadeEntrega.setBackground(Color.green);
               txt_fechaRegistrado.setBackground(Color.green);
               txt_costoEstudio.setBackground(Color.green);
               txt_ultimaModificacion.setText(user);
              
               JOptionPane.showMessageDialog(null, "Actualizacion correcta.");
               this.dispose();
               
            } catch (SQLException e){
               System.err.println("Error en actualizar estudio" + e);
               JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar paciente!!, contacte al programador.");
            }
    
        } else {
        }
        
        
        
    }//GEN-LAST:event_jButton_ActualizarEstudioActionPerformed

    private void txt_ultimaModificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ultimaModificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ultimaModificacionActionPerformed

    private void cmb_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_estatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JButton jButton_ActualizarEstudio;
    private javax.swing.JButton jButton_GenerarReporte;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_claveestudio;
    private javax.swing.JLabel jLabel_costoEstudio;
    private javax.swing.JLabel jLabel_diadeentrega;
    private javax.swing.JLabel jLabel_diaregistrado;
    private javax.swing.JLabel jLabel_estatus;
    private javax.swing.JLabel jLabel_indicaciones;
    private javax.swing.JLabel jLabel_modificadoPor;
    private javax.swing.JLabel jLabel_nombreestudio;
    private javax.swing.JLabel jLabel_tipodemuestra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane_indicaciones;
    private javax.swing.JTextField txt_claveEstudio;
    private javax.swing.JTextField txt_costoEstudio;
    private javax.swing.JTextField txt_diadeEntrega;
    private javax.swing.JTextField txt_fechaRegistrado;
    private javax.swing.JTextField txt_nombreEstudio;
    private javax.swing.JTextField txt_tipodeMuestra;
    private javax.swing.JTextField txt_ultimaModificacion;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {
     txt_claveEstudio.setText("");
     txt_nombreEstudio.setText("");
     txt_tipodeMuestra.setText("");
     txt_diadeEntrega.setText("");
     txt_fechaRegistrado.setText("");
     txt_costoEstudio.setText("");
     jTextPane_indicaciones.setText("");
    
    
    }


}
